### PR TITLE
ee3 to ee3

### PR DESCRIPTION
**Pull request by PSkaggs**
Merging ee3 to ee3 branches, instead of ee3 to master.

### CODE REVIEW

**Comment by PSkaggs** [comment]
I don't think I can resolve the merge conflicts because I don't have write access to your repo.  I believe if you just resolve them be keeping my changes everything should be fine.

**Comment by vmichnowicz** [comment]
Yeah, you can resolve the conflicts on your end. The "Use the command line" link tells you how:

Step 1: From your project repository, check out a new branch and test the changes.

```
git checkout -b PSkaggs-ee3 ee3
git pull https://github.com/PSkaggs/vwm_polls.git ee3
```

Step 2: Merge the changes and update on GitHub.

```
git checkout ee3
git merge --no-ff PSkaggs-ee3
git push origin ee3
```

Once you do that I can click a button and get your changes in the `ee3` branch.

**Comment by PSkaggs** [comment]
My bad, I should have checked for changes since the last time I pulled your repo down.  
Looks like it's good to go.  I installed it on a fresh EE3 copy and every thing seems to work fine, except it looks like the color chooser images is missing for the field options.  That is something that was changed with EE3 and I fixed it on a my clients installation, but I don't remember how at the moment.  It doesn't hinder choosing a color for the option you just can't see the color gradient in the picker.  I'll try and get to it at some point.

**Comment by vmichnowicz** [comment]
Thanks! Looks good man! :sunglasses:

**Pull request merged**
